### PR TITLE
Allow "major" as a value for assemblyVersion.precision

### PR DESCRIPTION
**Pull request by asherber**
Addresses #96. In addition to the items listed there, I also had to replace two instances of `default(VersionPrecision)` with `VersionPrecision.Minor`.

### CODE REVIEW

**Comment by asherber** [comment]
My bad, will fix. I'm having some problems getting your toolchain installed per instructions.

**Comment by asherber** [comment]
Ugh. The problem is that inserting `Major` as the first member of the enum, where it belongs, screws up all kinds of default handling (since `Major` is now the default instead of `Minor`). 

I can fix this with a bunch of small changes, or I can fix it by making `Major` the last member in the enum (not intuitive, but less intrusive). What do you think?

**Comment by asherber** [comment]
Sorry, I'm not having success with this -- I'm getting errors installing your toolchain, which means I can't build and run tests locally, which makes it hard to see what I'm missing. I'll close this pull request for now and come back to it when I can

**Comment by AArnott** [comment]
I don't think anything needs to be installed besides vs2015 for your work. What are you struggling with? 

Regarding Major, I suspect the right thing is to insert it at top, and fix up defaults.

**Comment by asherber** [comment]
`init.ps1` complains that it can't find the specified version of `NuProj`, and `build.ps1` throws a whole bunch of compilation errors in the `Tests` project. (Type or namespace does not exist, type or namespace does not exit.)

In VS 2015 Pro Update 3, I don't have the node.js or NuProj tools installed, so those projects don't load, but I see the same compilation errors in the Tests project

**Comment by AArnott** [comment]
The errors in build are probably because `init.ps1` doesn't finish. Can you please copy in the exact error output of that script?

**Comment by asherber** [comment]
```
PS> .\init.ps1
Restoring NuGet packages...
Unable to find version '0.10.30-beta-gcbd7693f91' of package 'NuProj'.
Restoring NPM packages...
Restoring Typings...
typings WARN deprecated 4/28/2016: "registry:dt/camel-case#0.0.0+20160316155526" is deprecated (updated, replaced or rem
oved)
typings WARN deprecated 11/21/2016: "registry:dt/node#6.0.0+20160915134512" is deprecated (updated, replaced or removed)


+-- del
| `-- pinkie-promise
|   `-- es6-promise
+-- request@2.69.0
| +-- form-data
| `-- tough-cookie
+-- camel-case (global)
`-- node (global)

P:\visual studio\nerdbank.gitversioning
PS>
```

**Comment by AArnott** [comment]
Thanks. That should be working. The package it can't find is in one of the nuget sources: https://www.myget.org/feed/aarnott/package/nuget/NuProj/0.10.30-beta-gcbd7693f91

Very strange. I'll look into this. Can you file a new issue with this init.ps1 output to track?

**Comment by asherber** [comment]
Now that I'm past that, I'm getting this from both `build.ps1` and VS:
```
BuildIntegrationTests.cs(854,107): error CS0122: 'ThisAssembly' is inaccessible due to its protection level [P:\visual studio\nerdbank.gitversioning\src\NerdBank.GitVersioning.Tests\NerdBank.GitVersioning.Tests.csproj]
```

**Comment by asherber** [comment]
It looks like no `xxx.Version.cs` file is being generated for the `Tests` project, so it's trying to read the (internal) class from the main project.

**Comment by AArnott** [comment]
It seems like you may be using a version of NuGet.exe other than the one init.ps1 downloads. 
How did you get past the NuProj restore failure?

**Comment by asherber** [comment]
Thanks for the NuGet fix. I'm now able to build and debug, and I see where tests are failing.

In `VersionOracle.GetAssemblyVersion()`, can you tell me why you set `assemblyVersion` to one value, and then immediately set it to a different value? It looks to me like that first line can just be ignored. I need to tweak this function, and I want to make sure I understand what you've got there. 
It looks to me like that first line can just be ignored.

**Pull request closed without merging**
