### PR TITLE
add latest runtime identifiers

### PR DESCRIPTION
**Pull request by ctaggart**
Same map as https://github.com/dotnet/sourcelink/pull/263

I noticed this drops the `corert` identifiers. Were those in the original import?

### CODE REVIEW

**Comment by AArnott** [comment]
Yes, those `corert` identifiers were present originally in the place I copied this from, but evidently [they removed them last December](https://github.com/dotnet/sourcelink/commit/d5ce73f7e782beb135376ea50d08d8448b21c263#diff-74c40ba3b1b98b0a00c3b4f9024180b9). Personally I have no reason to believe they are important for this library.

I see from #314 you're hoping this will start working on Alpine. Any reason not to add an Alpine 3.9 test in the azure-pipelines.yml file as part of this change by following this template?
https://github.com/AArnott/Nerdbank.GitVersioning/blob/01ebb81f18af1ce64659ad06267d86be96d1f8ad/azure-pipelines.yml#L133-L139

**Comment by AArnott** [comment]
Thanks, @ctaggart. Given the failure, I tried `docker run` of that same image locally and it just exited immediately. `/bin/bash` isn't present. Do you have any idea how to use/test this image so we can get this working?

**Comment by AArnott** [comment]
That's fine. We can just remove it. But would you mind removing the alpine test commit and your reverting commit from the PR before I complete it?

**Comment by ctaggart** [comment]
I'll try to test it locally now. Does the squash merge button work well for keeping a clean history on `master`?

**Comment by AArnott** [comment]
Sure. I'm happy to squash. I don't usually do it in case you're building on your branch in your fork for other things.

**Pull request merged**
