### PR TITLE
Update libgit2sharp

### LINKED ISSUE #314: LibGit2Sharp not working on sdk:2.2.105-alpine3.9
Steps to reproduce:
```
docker run --rm -it mcr.microsoft.com/dotnet/core/sdk:2.2.105-alpine3.9 sh
dotnet tool install -g nbgv
$HOME/.dotnet/tools/nbgv get-version
```

Error:
```
/ # $HOME/.dotnet/tools/nbgv get-version

Unhandled Exception: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'git2-a904fc6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libgit2-a904fc6: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path)
   at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths)
   at Nerdbank.GitVersioning.GitExtensions.OpenGitRepo(String pathUnderGitRepo, Boolean useDefaultConfigSearchPaths)
   at Nerdbank.GitVersioning.Tool.Program.OnGetVersionCommand(String projectPath, String format, String singleVariable, String versionOrRef) in D:\a\1\s\src\nbgv\Program.cs:line 261
   at Nerdbank.GitVersioning.Tool.Program.Main(String[] args) in D:\a\1\s\src\nbgv\Program.cs:line 131
Aborted
```

### PR DESCRIPTION
**Pull request by AArnott**
This will hopefully get alpine 3.9 to work

Closes #314 (if it works).

### CODE REVIEW

**Comment by ctaggart** [comment]
It failed for me:

```
PS C:\Users\taggac\github\Nerdbank.GitVersioning> docker run -it --rm -v ${PWD}:/src -w /src mcr.microsoft.com/dotnet/core/sdk:2.2.203-alpine3.9 sh
/src # dotnet tool install -g nbgv --add-source bin/nbgv/Release --version 2.3.145-gd103764fdd
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:

cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF

You can add it to the current session by running the following command:

export PATH="$PATH:/root/.dotnet/tools"

You can invoke the tool using the following command: nbgv
Tool 'nbgv' (version '2.3.145-gd103764fdd') was successfully installed.
/src # $HOME/.dotnet/tools/nbgv get-version

Unhandled Exception: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'git2-572e4d8' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libgit2-572e4d8: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path)
   at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths)
   at Nerdbank.GitVersioning.GitExtensions.OpenGitRepo(String pathUnderGitRepo, Boolean useDefaultConfigSearchPaths)
   at Nerdbank.GitVersioning.Tool.Program.OnGetVersionCommand(String projectPath, String format, String singleVariable, String versionOrRef) in C:\Users\taggac\github\Nerdbank.GitVersioning\src\nbgv\Program.cs:line 261
   at Nerdbank.GitVersioning.Tool.Program.Main(String[] args) in C:\Users\taggac\github\Nerdbank.GitVersioning\src\nbgv\Program.cs:line 131
Aborted
```

**Comment by AArnott** [comment]
I need to at least update the test script for alpine in Azure Pipelines to use `sh` instead of `bash`, I guess.

Regarding the failure you see, @ctaggart, I haven't tested on Alpine 3.9 yet myself. I expect you're right. There may be more I have to do to take advantage of @bording's work. I'm not sure.

**Comment by ctaggart** [comment]
Hmm, Alpine 3.8 ended up with a Segmentation fault:
```
PS C:\Users\taggac\github\Nerdbank.GitVersioning> docker run -it --rm -v ${PWD}:/src -w /src mcr.microsoft.com/dotnet/core/sdk:2.2.203-alpine3.8 sh
/src # dotnet tool install -g nbgv --add-source bin/nbgv/Release --version 2.3.145-gd103764fdd
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:

cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF

You can add it to the current session by running the following command:

export PATH="$PATH:/root/.dotnet/tools"

You can invoke the tool using the following command: nbgv
Tool 'nbgv' (version '2.3.145-gd103764fdd') was successfully installed.
/src # $HOME/.dotnet/tools/nbgv get-version
Segmentation fault
```

**Comment by AArnott** [comment]
I see the segfault on Alpine 3.8 as well, @ctaggart. Do you have reason to believe this _ever_ worked on some version of Alpine?

**Comment by AArnott** [comment]
So I see segfault in Alpine 3.8, but in 3.9 I get further. @bording, the LD_DEBUG env var has no effect here. Any idea why?

```
/src # export LD_DEBUG=all
/src # echo $LD_DEBUG
all
/src #  $HOME/.dotnet/tools/nbgv get-version -p src/

Unhandled Exception: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'git2-572e4d8' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libgit2-572e4d8: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path)
   at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths)
   at Nerdbank.GitVersioning.GitExtensions.OpenGitRepo(String pathUnderGitRepo, Boolean useDefaultConfigSearchPaths)
   at Nerdbank.GitVersioning.Tool.Program.OnGetVersionCommand(String projectPath, String format, String singleVariable, String versionOrRef) in D:\git\Nerdbank.GitVersioning\src\nbgv\Program.cs:line 266
   at Nerdbank.GitVersioning.Tool.Program.Main(String[] args) in D:\git\Nerdbank.GitVersioning\src\nbgv\Program.cs:line 131
Aborted
```

**Comment by ctaggart** [comment]
I think it would be good to add the Alpine 3.8 tests in another branch to see that it does work, yet it is broken in this one.

**Comment by bording** [comment]
> So I see segfault in Alpine 3.8, but in 3.9 I get further. @bording, the LD_DEBUG env var has no effect here. Any idea why?

@AArnott Are you invoking that from a container? Since the LD_DEBUG output is going to stderr, maybe you aren't seeing that from how the container output is showing. Try and redirect it to a file using `2>` and see if the file is in the container.

As far as why you might be seeing some errors about not finding the assembly, do you know which versions of the .NET Core SDK & Runtime you're using? I know that the alpine 3.8 and 3.9 RIDs only made it in recently. Based on https://github.com/dotnet/corefx/issues/34316#issuecomment-474102877, you need to be on the 2.1.9 or 2.2.3 runtimes to support it.

If you're seeing segfaults, then there's a chance that libgit2 might have problems with musl-based linux, which I've heard rumors of in the past.

@ctaggart You said things were working on 3.8 in https://github.com/AArnott/Nerdbank.GitVersioning/issues/314#issuecomment-483924148 though.

**Comment by AArnott** [comment]
I tried it locally and I believe it segfaulted on 3.8 without any changes from this PR.
Nothing here works on Azure Pipelines though, becaues Azure Pipelines is failing to launch bash, since Alpine doesn't ship with it. I'm trying to research how to workaround this. [bash is a documented requirement](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#requirements).

**Comment by AArnott** [comment]
> Try and redirect it to a file using 2> and see if the file is in the container.

I did. No dice. The only stderr output is what also appeared on the screen that I included above.

> As far as why you might be seeing some errors about not finding the assembly, do you know which versions of the .NET Core SDK & Runtime you're using? 

We're using the dotnet SDK and runtime that are shipped in the image by Microsoft. So I'm pretty sure it's a matching set. :)

**Comment by bording** [comment]
> We're using the dotnet SDK and runtime that are shipped in the image by Microsoft. So I'm pretty sure it's a matching set. :)

I wasn't implying they were mismatched, just trying to make sure you're using at least the minimum version required to have the alpine RIDs.  The 2.2.105 does look to be new enough, though.

> I did. No dice. The only stderr output is what also appeared on the screen that I included above.

Hmm. Not sure why it would make a difference, but did you try setting it on the same line as the invoking the command instead of exporting it?

**Comment by AArnott** [comment]
> did you try setting it on the same line where you're invoking the command instead of exporting it?

Yes, that was the first thing I tried.

**Comment by bording** [comment]
After doing a bit of research, I now understand why `LD_DEBUG` isn't working. That environment variable controls the behavior of the dynamic linker, which is something provided as part of glibc. Since Alpine is using musl libc, it's using the musl dynamic linker instead.

Looking at the musl dynamic linker source, it doesn't even look for the LD_DEBUG environment variable.

I haven't been able to find a replacement option for debugging linking problems yet, either.

**Comment by AArnott** [comment]
Bummer. I guess Alpine is good for something... right? Being small maybe? ;-p

**Comment by bording** [comment]
I'll try and get a simpler scenario working, just a basic use of LibGit2Sharp on Alpine, which should help determine where the problem is.

**Comment by bording** [comment]
Okay, so here's what the problem is: [The latest 2.2 .NET Core SDKs don't actually have the updated RID graph package](https://github.com/dotnet/sdk/issues/3037#issuecomment-481902382) even though ti was updated for Alpine 3.8 and 3.9, so it just detects the RID as `linux-musl-x64`, so the correct binary isn't being loaded. 🙄 

Per the linked issue, it looks like the latest 2.1 SDK did get the updated RID graph, so try using `mcr.microsoft.com/dotnet/core/sdk:2.1.505-alpine3.9` and see what difference that makes. I was able to make my simple project work with that image.

In theory, you're supposed to be able to set the `DOTNET_RUNTIME_ID` environment variable to the RID you want it to be, but it didn't seem to be working. When using the 2.2 SDK, I was still getting an error even though I had it set to `alpine.3.9-x64`.

**Comment by ctaggart** [comment]
`2.1.505-alpine3.9` works!

```
PS C:\Users\taggac\github\Nerdbank.GitVersioning> docker run --name nbgv -it --rm -v ${PWD}:/src -w /src mcr.microsoft.com/dotnet/core/sdk:2.1.505-alpine3.9
/src # dotnet tool install -g nbgv --add-source bin/nbgv/Debug --version 2.3.146-g4f65ba94f7
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:

cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF

You can add it to the current session by running the following command:

export PATH="$PATH:/root/.dotnet/tools"

You can invoke the tool using the following command: nbgv
Tool 'nbgv' (version '2.3.146-g4f65ba94f7') was successfully installed.
/src # $HOME/.dotnet/tools/nbgv get-version
Version:                      0.0.346.25935
AssemblyVersion:              0.0.0.0
AssemblyInformationalVersion: 0.0.346+4f65ba94f7
NuGet package Version:        0.0.346-4f65ba94f7
NPM package Version:          0.0.346-4f65ba94f7
/src #
```

**Comment by ctaggart** [comment]
The `DOTNET_RUNTIME_ID` override doesn't appear to work for the runtime:

```
PS C:\Users\taggac\github\Nerdbank.GitVersioning> docker run --name nbgv -it --rm -v ${PWD}:/src -w /src -e DOTNET_RUNTIME_ID=alpine.3.9-x64 mcr.microsoft.com/dotnet/core/sdk:2.2.203-alpine3.9
/src # echo $DOTNET_RUNTIME_ID
alpine.3.9-x64
/src # dotnet tool install -g nbgv --add-source bin/nbgv/Debug --version 2.3.146-g4f65ba94f7
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:

cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF

You can add it to the current session by running the following command:

export PATH="$PATH:/root/.dotnet/tools"

You can invoke the tool using the following command: nbgv
Tool 'nbgv' (version '2.3.146-g4f65ba94f7') was successfully installed.
/src # $HOME/.dotnet/tools/nbgv get-version

Unhandled Exception: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'git2-572e4d8' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libgit2-572e4d8: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_opts(Int32 option, UInt32 level, String path)
   at LibGit2Sharp.GlobalSettings.SetConfigSearchPaths(ConfigurationLevel level, String[] paths)
   at Nerdbank.GitVersioning.GitExtensions.OpenGitRepo(String pathUnderGitRepo, Boolean useDefaultConfigSearchPaths)
   at Nerdbank.GitVersioning.Tool.Program.OnGetVersionCommand(String projectPath, String format, String singleVariable, String versionOrRef) in C:\Users\taggac\github\Nerdbank.GitVersioning\src\nbgv\Program.cs:line 266
   at Nerdbank.GitVersioning.Tool.Program.Main(String[] args) in C:\Users\taggac\github\Nerdbank.GitVersioning\src\nbgv\Program.cs:line 131
Aborted
/src #
```

**Comment by bording** [comment]
> The DOTNET_RUNTIME_ID override doesn't appear to work for the runtime:

@ctaggart Yeah, I found documentation talking about it saying that it should work, but it doesn't.

**Comment by AArnott** [comment]
Well, we still have the problem that Azure pipelines doesn't like docker images that lack bash. 😕

**Comment by AArnott** [comment]
I can remove the test validation though so we can complete this PR, if it otherwise had what unblocks you, @ctaggart

**Comment by ctaggart** [comment]
That would be great!

**Pull request merged**
